# Generated by Django 3.1.6 on 2021-04-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=50)),
                ('lithography', models.CharField(max_length=50)),
                ('cache', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('motherboards', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('generation', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
