# Generated by Django 3.1.6 on 2021-04-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='processor',
            new_name='ram',
        ),
    ]
