# Generated by Django 3.1.6 on 2021-04-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210405_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='ram',
            new_name='name',
        ),
    ]
