# Generated by Django 3.1.6 on 2021-04-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210407_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='name',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
