# Generated by Django 3.1.7 on 2021-04-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=512)),
                ('brand', models.CharField(default=None, max_length=20)),
                ('model', models.CharField(default=None, max_length=50)),
                ('socket', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
                ('ram_slots', models.IntegerField(max_length=50)),
                ('max_ram', models.IntegerField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('imageurl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=512)),
                ('brand', models.CharField(default=None, max_length=512)),
                ('socket', models.CharField(default=None, max_length=512)),
                ('cores', models.IntegerField(default=None, max_length=512)),
                ('base_clock', models.IntegerField(default=None, max_length=512)),
                ('boost_clock', models.IntegerField(default=None, max_length=512)),
                ('tdp', models.IntegerField(default=None, max_length=512)),
                ('integrated_graphics', models.CharField(default=None, max_length=512)),
                ('multithreading', models.BooleanField(default=None, max_length=512)),
                ('price', models.CharField(default=None, max_length=512)),
                ('imageurl', models.CharField(default=None, max_length=512)),
                ('motherboard', models.CharField(default=None, max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='MP',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
    ]
