# Generated by Django 3.1.7 on 2021-04-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210425_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='max_ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_slots',
            field=models.IntegerField(),
        ),
    ]
