# Generated by Django 3.1.7 on 2021-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210425_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='imageurl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='max_ram',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_slots',
            field=models.IntegerField(null=True),
        ),
    ]
