# Generated by Django 3.1.7 on 2021-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210425_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='imageurl',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='max_ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_slots',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processor',
            name='boost_clock',
            field=models.IntegerField(default=None, max_length=512, null=True),
        ),
    ]
