# Generated by Django 3.1.7 on 2021-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210425_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='base_clock',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='processor',
            name='boost_clock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='cores',
            field=models.IntegerField(default=None),
        ),
    ]
