# Generated by Django 3.1.7 on 2021-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210425_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='imageurl',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='processor',
            name='imageurl',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
