# Generated by Django 3.1.7 on 2021-04-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210425_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='brand',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='processor',
            name='cores',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processor',
            name='imageurl',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='processor',
            name='motherboard',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='processor',
            name='multithreading',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='processor',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='processor',
            name='price',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='processor',
            name='socket',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='processor',
            name='tdp',
            field=models.IntegerField(default=None),
        ),
    ]
