# Generated by Django 3.1.7 on 2021-04-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210425_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='imageurl',
        ),
    ]
