# Generated by Django 3.1.7 on 2021-04-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_processor_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='imageurl',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processor',
            name='base_clock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processor',
            name='boost_clock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processor',
            name='integrated_graphics',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
