# Generated by Django 3.1.7 on 2021-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='boost_clock',
            field=models.IntegerField(null=True),
        ),
    ]
