# Generated by Django 3.1.7 on 2021-04-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_delete_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=10)),
                ('storage', models.IntegerField(max_length=5)),
                ('frequency', models.IntegerField(max_length=5)),
                ('generation', models.CharField(default='ddr4', max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('imageurl', models.CharField(max_length=2000)),
            ],
        ),
    ]
