# Generated by Django 3.1.7 on 2021-04-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ram',
            name='storage',
            field=models.IntegerField(),
        ),
    ]
