# Generated by Django 3.1.7 on 2021-04-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210426_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USER',
        ),
    ]
