# Generated by Django 3.1.7 on 2021-04-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USER',
        ),
    ]
