# Generated by Django 3.1.7 on 2021-04-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210427_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USER',
        ),
    ]
