# Generated by Django 3.1.7 on 2021-04-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motherboard',
        ),
        migrations.DeleteModel(
            name='Processor',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='USER',
        ),
    ]
