# Generated by Django 3.1.7 on 2021-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0039_auto_20210427_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='POWERSUPPLY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('imageurl', models.CharField(max_length=100)),
                ('watt', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
