# Generated by Django 3.1.7 on 2021-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0044_auto_20210427_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
