# Generated by Django 3.1.7 on 2021-04-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_motherboard_powersupply_processor_ram_ssd_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=100)),
                ('imageurl', models.CharField(max_length=100)),
                ('generation', models.CharField(max_length=10)),
                ('storage', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='processor',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
