# Generated by Django 3.1.7 on 2021-04-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210428_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('resolution', models.CharField(max_length=20)),
                ('imageurl', models.CharField(max_length=100)),
            ],
        ),
    ]
